#!/bin/sh

# Stashes from current branch & pops stash to new given branch

newBranch=$1

if [ ! -z "$1" ]
then
  git stash
  git checkout -b $newBranch
  git stash pop
else
  echo "Branch name is not specified"
fi